Add new router
Domiik/LoginNoStoryboard pull request #3
Opened 2021-09-25 18:29 UTC by Domiik

Moved login and password in enum action
Add registration view
add sceneDelegate

2021-09-27 19:35 UTC, s-glagolev requested changes

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/Model/User.swift
>      var name: String!
мы обсуждали то, что не обязательно в текущей задаче хранить какие либо поля для данной структуры. получается надо их убрать

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/SceneDelegate.swift
> +        if UserDefaults.standard.bool(forKey: "Login"){
давай откажемся от переменно типа bool и в UserDefaults будем хранить структуру User. У данной структуры не будет никаких полей.

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/View/Login/LoginView.swift
> +    let loginText: UILabel = {
возьми за правило, всегда, когда создаешь любой элемент из UIKIt инициализировать через lazy var

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/View/Registration/RegistrationView.swift
> +            maker.left.equalToSuperview().inset(50)
попробуй использовать .edges().equalToSuperView().inset(UIEdgesInset())

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/View/Registration/RegistrationView.swift
> +    let registrationText: UILabel = {
lazy var

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/View/Registration/RegistrationView.swift
> +    let loginTextField: UITextField = {
lazy var

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/View/Registration/RegistrationView.swift
> +    let passwordTextField: UITextField = {
lazy var

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/View/Registration/RegistrationView.swift
> +    let сonfirmedPasswordTextField: UITextField = {
lazy var

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/View/Registration/RegistrationView.swift
> +    let buttonRegister: UIButton = {
lazy var

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/View/Registration/RegistrationViewController.swift
> +        navigationController?.navigationBar.isHidden = false
лучше использовать setHiddenNavigationBar(). потому что тогда сохраниться анимация, когда это необходимо

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/ViewModel/UserViewModel.swift
> +            UserDefaults.standard.set(true, forKey: "Login")
Аналогично SceneDelegate. сделай сохранение User()

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/ViewModel/UserViewModel.swift
> +            UserDefaults.standard.set(true, forKey: "Login")
Так же почитай про PropertyWrapper

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/Router/Router.swift
> +protocol Router {
Не вижу смысла в этом протоколе. По сути ты дублируешь название функций и получается, что это лишние нажатия на клавиатуру)
1) Я бы на твоем месте не начинал сначала писать протокол, а начинал бы писать класс.
2) Если бы писал протокол, то функцию navigate определил бы тоже в протоколе.

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/Router/Router.swift
> +protocol Router {
Пока что давай не пользоваться протоколами. Хорошо, что ты их знаешь) но это пока лишнее. Давай пока от них избавимся)

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/Router/LoginRouter.swift
>  class DefaultLoginRouter: LoginRouter {
Аналогично DefaultRouter

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/Router/AppRouter.swift
> +protocol AppRouter {
Аналогично DefaultRouter.

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/Router/Router.swift
> +    weak var viewController: SceneDelegate!
Смотри разночтение, лучше так не делать если ты передаешь суда SceneDelegate, то и переменная должна называться так же

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/Router/Router.swift
> +    required init(viewController: SceneDelegate) {
Лучше суда передавать не SceneDelegate, а UIWindow

2021-09-27 19:35 UTC, s-glagolev commented on LoginNoStoryboard/Router/Router.swift
> +
Так же полезно было бы иметь метод start() (к примеру), который и запускает выбор экрана исходя из состояния приложения. Это как раз ответственность сущности типа Router.

2021-09-30 08:01 UTC, Domiik commented on LoginNoStoryboard/View/Registration/RegistrationViewController.swift
> +        navigationController?.navigationBar.isHidden = false
navigationController?.setNavigationBarHidden(false, animated: animated)
При использовании вот этого кода не появляется navigation Bar

2021-10-02 12:09 UTC, merged